learningTemplates/basic_app/urls.py
from django.urls import path
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns = [
	path('index/',views.index,name='index'),
	path('relative/',views.relative,name='relative'),
	path('other/',views.other, name='other'),
]

learningTemplates/learningTemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls'))

]

learningTemplates/basic_app/models.py
from django.db import models

# Create your models here.

learningTemplates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	context_dict = {'text':'hello world','number':100}
	return render(request,"basic_app/index.html", context=context_dict)
def other(Request):
	return render(Request, "basic_app/other.html")
def relative(Request):
	return render(Request, "basic_app/relative_templates.html")

learningTemplates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:index' %}">Sam Jones</a>
       <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:relative' %}"> Relative Templates</a>
      	 <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>

 <div class="container">
 	{% block body_block %}
 	<!-- anything outside of this will be inherited if you extend -->
 	{% endblock %}
 </div>
</body>
</html>

learningTemplates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html"%}
{% block body_block%}
<h1> Index Page</h1>	
<h1>{{ text | cut:'hello' }} </h1>
<h1> {{ number|add:"23" }} </h1>
{%endblock%}

learningTemplates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
	<h1> Other page </h1>
	<h2> this is template inheritance </h2>
	{% endblock %}	

</body>
</html>

learningTemplates/templates/basic_app/relative_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}
<h1> Relative Template </h1>
<h2> Yolo</h2>
{%endblock%}

learningTemplates/templates/index.html
<!DOCTYPE HTML>
{%extends base.html%}
{%block bodyblock%}
<h1> Main Index page in /templates.</h1>
{% endblock %}